// Auto-extracted translation data — logic lives in the page component.

export const TX = {
  title:      { de: 'Trainiere deinen Zwilling', en: 'Train your twin', es: 'Entrena tu gemelo', fr: 'Entraîne ton jumeau', pt: 'Treine seu gêmeo', ar: 'درّب توأمك', zh: '训练你的孪生', ja: 'ツインを訓練する', hi: 'अपना जुड़वां प्रशिक्षित करें', ru: 'Обучи своего двойника', id: 'Latih kembaranmu', tr: 'İkizini eğit', ko: '트윈을 훈련시키세요', it: 'Allena il tuo gemello', nl: 'Train jouw tweeling', pl: 'Trenuj swojego bliźniaka', uk: 'Навчи свого двійника', vi: 'Huấn luyện sinh đôi', bn: 'তোমার যমজ প্রশিক্ষণ দাও', fa: 'دوقلوی خود را آموزش دهید' },
  sub:        { de: 'Wo stehst du? 8 Dimensionen — kein Login, kein Server.', en: 'Where do you stand? 8 dimensions — no login, no server.', es: '¿Dónde estás? 8 dimensiones — sin inicio de sesión, sin servidor.', fr: 'Où te situes-tu? 8 dimensions — sans connexion, sans serveur.', pt: 'Onde você está? 8 dimensões — sem login, sem servidor.', ar: 'أين تقف؟ 8 أبعاد — بدون تسجيل دخول، بدون خادم.', zh: '你站在哪里？8个维度——无需登录，无需服务器。', ja: 'あなたはどこに立っていますか？8次元 — ログインなし、サーバーなし。', hi: 'आप कहाँ खड़े हैं? 8 आयाम — कोई लॉगिन नहीं, कोई सर्वर नहीं।', ru: 'Где вы стоите? 8 измерений — без входа в систему, без сервера.', id: 'Di mana posisimu? 8 dimensi — tanpa login, tanpa server.', tr: 'Nerede duruyorsun? 8 boyut — giriş yok, sunucu yok.', ko: '어디에 서 있나요? 8가지 차원 — 로그인 없음, 서버 없음.', it: 'Dove stai? 8 dimensioni — nessun login, nessun server.', nl: 'Waar sta jij? 8 dimensies — geen login, geen server.', pl: 'Gdzie stoisz? 8 wymiarów — bez logowania, bez serwera.', uk: 'Де ви стоїте? 8 вимірів — без входу, без сервера.', vi: 'Bạn đứng ở đâu? 8 chiều — không đăng nhập, không máy chủ.', bn: 'তুমি কোথায় দাঁড়িয়ে? ৮ মাত্রা — কোনো লগইন নেই, কোনো সার্ভার নেই।', fa: 'کجا ایستاده‌اید؟ ۸ بُعد — بدون ورود، بدون سرور.' },
  demo_sec:   { de: 'Über dich', en: 'About you', es: 'Sobre ti', fr: 'À ton sujet', pt: 'Sobre você', ar: 'عنك', zh: '关于你', ja: 'あなたについて', hi: 'आपके बारे में', ru: 'О вас', id: 'Tentang kamu', tr: 'Senin hakkında', ko: '나에 대해', it: 'Su di te', nl: 'Over jou', pl: 'O tobie', uk: 'Про вас', vi: 'Về bạn', bn: 'তোমার সম্পর্কে', fa: 'درباره شما' },
  demo_sub:   { de: 'Optional — macht deinen Zwilling regional wertvoller.', en: 'Optional — makes your twin more valuable for regional politics.', es: 'Opcional — hace que tu gemelo sea más valioso para la política regional.', fr: 'Optionnel — rend ton jumeau plus précieux pour la politique régionale.', pt: 'Opcional — torna seu gêmeo mais valioso para a política regional.', ar: 'اختياري — يجعل توأمك أكثر قيمة للسياسة الإقليمية.', zh: '可选 — 使您的孪生对地区政治更有价值。', ja: 'オプション — あなたのツインを地域政治により価値あるものにします。', hi: 'वैकल्पिक — आपके जुड़वां को क्षेत्रीय राजनीति के लिए अधिक मूल्यवान बनाता है।', ru: 'Необязательно — делает вашего двойника более ценным для региональной политики.', id: 'Opsional — membuat kembaranmu lebih berharga untuk politik regional.', tr: 'İsteğe bağlı — ikizini bölgesel siyaset için daha değerli yapar.', ko: '선택 사항 — 트윈을 지역 정치에 더 가치 있게 만듭니다.', it: 'Opzionale — rende il tuo gemello più prezioso per la politica regionale.', nl: 'Optioneel — maakt jouw tweeling waardevoller voor regionale politiek.', pl: 'Opcjonalne — sprawia, że twój bliźniak jest cenniejszy dla lokalnej polityki.', uk: 'Необов\'язково — робить вашого двійника більш цінним для регіональної політики.', vi: 'Tùy chọn — làm cho sinh đôi của bạn có giá trị hơn cho chính trị khu vực.', bn: 'ঐচ্ছিক — তোমার যমজকে আঞ্চলিক রাজনীতির জন্য আরো মূল্যবান করে।', fa: 'اختیاری — دوقلوی شما را برای سیاست منطقه‌ای ارزشمندتر می‌کند.' },
  age_lbl:    { de: 'Altersgruppe', en: 'Age group', es: 'Grupo de edad', fr: 'Groupe d\'âge', pt: 'Faixa etária', ar: 'الفئة العمرية', zh: '年龄组', ja: '年齢層', hi: 'आयु वर्ग', ru: 'Возрастная группа', id: 'Kelompok usia', tr: 'Yaş grubu', ko: '연령대', it: 'Gruppo di età', nl: 'Leeftijdsgroep', pl: 'Grupa wiekowa', uk: 'Вікова група', vi: 'Nhóm tuổi', bn: 'বয়সের গোষ্ঠী', fa: 'گروه سنی' },
  country_lbl:{ de: 'Land', en: 'Country', es: 'País', fr: 'Pays', pt: 'País', ar: 'البلد', zh: '国家', ja: '国', hi: 'देश', ru: 'Страна', id: 'Negara', tr: 'Ülke', ko: '국가', it: 'Paese', nl: 'Land', pl: 'Kraj', uk: 'Країна', vi: 'Quốc gia', bn: 'দেশ', fa: 'کشور' },
  region_lbl: { de: 'Bundesland / Region', en: 'State / Region', es: 'Estado / Región', fr: 'Région / État', pt: 'Estado / Região', ar: 'المنطقة', zh: '省/州', ja: '州/地域', hi: 'राज्य / क्षेत्र', ru: 'Регион', id: 'Provinsi / Wilayah', tr: 'Bölge', ko: '주/지역', it: 'Regione', nl: 'Provincie', pl: 'Region', uk: 'Область', vi: 'Tỉnh/Khu vực', bn: 'রাজ্য / অঞ্চল', fa: 'استان / منطقه' },
  finish:     { de: 'Zwilling speichern', en: 'Save twin', es: 'Guardar gemelo', fr: 'Enregistrer le jumeau', pt: 'Salvar gêmeo', ar: 'حفظ التوأم', zh: '保存孪生', ja: 'ツインを保存', hi: 'जुड़वां सहेजें', ru: 'Сохранить двойника', id: 'Simpan kembaran', tr: 'İkizi kaydet', ko: '트윈 저장', it: 'Salva gemello', nl: 'Tweeling opslaan', pl: 'Zapisz bliźniaka', uk: 'Зберегти двійника', vi: 'Lưu sinh đôi', bn: 'যমজ সংরক্ষণ', fa: 'ذخیره دوقلو' },
  privacy:    { de: 'Alles lokal. Kein Account, keine Cloud.', en: 'All local. No account, no cloud.', es: 'Todo local. Sin cuenta, sin nube.', fr: 'Tout est local. Aucun compte, aucun cloud.', pt: 'Tudo local. Sem conta, sem nuvem.', ar: 'كل شيء محلي. لا حساب، لا سحابة.', zh: '一切本地。无账户，无云端。', ja: 'すべてローカル。アカウントなし、クラウドなし。', hi: 'सब कुछ स्थानीय। कोई खाता नहीं, कोई क्लाउड नहीं।', ru: 'Всё локально. Без аккаунта, без облака.', id: 'Semua lokal. Tanpa akun, tanpa cloud.', tr: 'Her şey yerel. Hesap yok, bulut yok.', ko: '모두 로컬. 계정 없음, 클라우드 없음.', it: 'Tutto in locale. Nessun account, nessun cloud.', nl: 'Alles lokaal. Geen account, geen cloud.', pl: 'Wszystko lokalnie. Brak konta, brak chmury.', uk: 'Все локально. Без аккаунту, без хмари.', vi: 'Tất cả cục bộ. Không tài khoản, không đám mây.', bn: 'সব স্থানীয়। কোনো অ্যাকাউন্ট নেই, কোনো ক্লাউড নেই।', fa: 'همه چیز محلی است. بدون حساب، بدون ابر.' },
  archetype_lbl: { de: 'Profil', en: 'Profile', es: 'Perfil', fr: 'Profil', pt: 'Perfil', ar: 'الملف الشخصي', zh: '档案', ja: 'プロフィール', hi: 'प्रोफ़ाइल', ru: 'Профиль', id: 'Profil', tr: 'Profil', ko: '프로필', it: 'Profilo', nl: 'Profiel', pl: 'Profil', uk: 'Профіль', vi: 'Hồ sơ', bn: 'প্রোফাইল', fa: 'پروفایل' },
};


