// Auto-extracted translation data — logic lives in the page component.

export const TX = {
  title:      { de: 'Einblicke', en: 'Insights', es: 'Perspectivas', fr: 'Analyses', pt: 'Perspectivas', ar: 'رؤى', zh: '洞察', ja: 'インサイト', hi: 'अंतर्दृष्टि', ru: 'Аналитика', id: 'Wawasan', tr: 'Analizler', ko: '인사이트', it: 'Analisi', nl: 'Inzichten', pl: 'Analizy', uk: 'Аналітика', vi: 'Phân tích', bn: 'অন্তর্দৃষ্টি', fa: 'بینش‌ها' },
  subtitle:   { de: 'Was 2.500 digitale Zwillinge aus 44 Ländern uns sagen', en: 'What 2,500 digital twins from 44 countries tell us', es: 'Lo que nos dicen 2.500 gemelos digitales de 44 países', fr: 'Ce que nous disent 2 500 jumeaux numériques de 44 pays', pt: 'O que nos dizem 2.500 gêmeos digitais de 44 países', ar: 'ما يخبرنا به 2500 توأم رقمي من 44 دولة', zh: '来自44个国家的2500个数字孪生告诉我们什么', ja: '44カ国2,500のデジタルツインが語ること', hi: '44 देशों से 2,500 डिजिटल जुड़वां हमें क्या बताते हैं', ru: 'Что говорят нам 2500 цифровых двойников из 44 стран', id: 'Apa yang disampaikan 2.500 kembaran digital dari 44 negara', tr: '44 ülkeden 2.500 dijital ikizin bize anlattıkları', ko: '44개국 2,500개 디지털 트윈이 우리에게 말해주는 것', it: 'Cosa ci dicono 2.500 gemelli digitali da 44 paesi', nl: 'Wat 2.500 digitale tweelingen uit 44 landen ons vertellen', pl: 'Co mówią nam 2500 cyfrowych bliźniaków z 44 krajów', uk: 'Що говорять нам 2500 цифрових двійників з 44 країн', vi: 'Điều 2.500 sinh đôi kỹ thuật số từ 44 quốc gia cho chúng ta biết', bn: '৪৪টি দেশ থেকে ২,৫০০ ডিজিটাল যমজ আমাদের কী বলে', fa: 'آنچه ۲٫۵۰۰ دوقلوی دیجیتال از ۴۴ کشور به ما می‌گویند' },
  most_div:   { de: 'Umstrittenste Fragen', en: 'Most divided questions', es: 'Preguntas más divididas', fr: 'Questions les plus divisées', pt: 'Perguntas mais divididas', ar: 'الأسئلة الأكثر انقساماً', zh: '最具争议的问题', ja: '最も意見が分かれる質問', hi: 'सबसे विभाजित प्रश्न', ru: 'Самые спорные вопросы', id: 'Pertanyaan paling terbagi', tr: 'En tartışmalı sorular', ko: '가장 의견이 갈리는 질문', it: 'Domande più divise', nl: 'Meest verdeelde vragen', pl: 'Najbardziej podzielone pytania', uk: 'Найбільш суперечливі питання', vi: 'Câu hỏi gây chia rẽ nhất', bn: 'সবচেয়ে বিভক্ত প্রশ্ন', fa: 'بحث‌برانگیزترین سؤالات' },
  most_con:   { de: 'Stärkster Konsens', en: 'Strongest consensus', es: 'Mayor consenso', fr: 'Plus fort consensus', pt: 'Maior consenso', ar: 'أقوى توافق', zh: '最强共识', ja: '最も強いコンセンサス', hi: 'सबसे मजबूत सहमति', ru: 'Наибольший консенсус', id: 'Konsensus terkuat', tr: 'En güçlü mutabakat', ko: '가장 강한 합의', it: 'Massimo consenso', nl: 'Sterkste consensus', pl: 'Najsilniejszy konsens', uk: 'Найсильніший консенсус', vi: 'Đồng thuận mạnh nhất', bn: 'সবচেয়ে শক্তিশালী ঐকমত্য', fa: 'قوی‌ترین اجماع' },
  topic_heat: { de: 'Politisches Thermostat', en: 'Political thermostat', es: 'Termostato político', fr: 'Thermomètre politique', pt: 'Termômetro político', ar: 'الترموستات السياسي', zh: '政治温度计', ja: '政治サーモスタット', hi: 'राजनीतिक थर्मोस्टैट', ru: 'Политический термостат', id: 'Termometer politik', tr: 'Siyasi termometre', ko: '정치적 온도계', it: 'Termometro politico', nl: 'Politieke thermostaat', pl: 'Polityczny termometr', uk: 'Політичний термометр', vi: 'Nhiệt kế chính trị', bn: 'রাজনৈতিক থার্মোস্ট্যাট', fa: 'ترموستات سیاسی' },
  topic_desc: { de: 'Globaler Durchschnitt pro Dimension', en: 'Global average per dimension', es: 'Promedio global por dimensión', fr: 'Moyenne globale par dimension', pt: 'Média global por dimensão', ar: 'المتوسط العالمي لكل بُعد', zh: '每个维度的全球平均值', ja: '各次元のグローバル平均', hi: 'प्रत्येक आयाम का वैश्विक औसत', ru: 'Глобальное среднее по каждому измерению', id: 'Rata-rata global per dimensi', tr: 'Boyut başına küresel ortalama', ko: '차원별 글로벌 평균', it: 'Media globale per dimensione', nl: 'Globaal gemiddelde per dimensie', pl: 'Globalna średnia na wymiar', uk: 'Глобальне середнє по кожному виміру', vi: 'Trung bình toàn cầu theo chiều', bn: 'প্রতিটি মাত্রার বৈশ্বিক গড়', fa: 'میانگین جهانی به ازای هر بُعد' },
  outliers:   { de: 'Länder die am meisten abweichen', en: 'Countries that diverge most', es: 'Países que más divergen', fr: 'Pays qui divergent le plus', pt: 'Países que mais divergem', ar: 'الدول الأكثر انحرافاً', zh: '偏差最大的国家', ja: '最も乖離している国', hi: 'सबसे अधिक विचलित होने वाले देश', ru: 'Страны с наибольшим отклонением', id: 'Negara-negara yang paling menyimpang', tr: 'En çok ayrışan ülkeler', ko: '가장 많이 벗어나는 국가들', it: 'Paesi che si discostano di più', nl: 'Landen die het meest afwijken', pl: 'Kraje, które najbardziej się różnią', uk: 'Країни, що найбільше відхиляються', vi: 'Các quốc gia có sự khác biệt lớn nhất', bn: 'সবচেয়ে বেশি বিচ্যুত দেশগুলো', fa: 'کشورهایی که بیشترین انحراف را دارند' },
  view_q:     { de: 'Frage ansehen →', en: 'View question →', es: 'Ver pregunta →', fr: 'Voir la question →', pt: 'Ver pergunta →', ar: 'عرض السؤال ←', zh: '查看问题 →', ja: '質問を見る →', hi: 'प्रश्न देखें →', ru: 'Открыть вопрос →', id: 'Lihat pertanyaan →', tr: 'Soruyu gör →', ko: '질문 보기 →', it: 'Vedi domanda →', nl: 'Bekijk vraag →', pl: 'Zobacz pytanie →', uk: 'Переглянути питання →', vi: 'Xem câu hỏi →', bn: 'প্রশ্ন দেখুন →', fa: 'مشاهده سؤال ←' },
};


