// Auto-extracted translation data — logic lives in the page component.

export const TX = {
  back:        { de: '← Zurück', en: '← Back', es: '← Volver', fr: '← Retour', pt: '← Voltar', ar: '← رجوع', zh: '← 返回', ja: '← 戻る', hi: '← वापस', ru: '← Назад', id: '← Kembali', tr: '← Geri', ko: '← 뒤로', it: '← Indietro', nl: '← Terug', pl: '← Wróć', uk: '← Назад', vi: '← Quay lại', bn: '← ফিরে যান', fa: '← بازگشت' },
  support:     { de: 'dafür', en: 'support', es: 'a favor', fr: 'pour', pt: 'a favor', ar: 'مؤيد', zh: '支持', ja: '支持', hi: 'पक्ष में', ru: 'за', id: 'mendukung', tr: 'destek', ko: '찬성', it: 'a favore', nl: 'voor', pl: 'za', uk: 'за', vi: 'ủng hộ', bn: 'সমর্থন', fa: 'موافق' },
  oppose:      { de: 'dagegen', en: 'oppose', es: 'en contra', fr: 'contre', pt: 'contra', ar: 'معارض', zh: '反对', ja: '反対', hi: 'विरोध में', ru: 'против', id: 'menolak', tr: 'karşı', ko: '반대', it: 'contro', nl: 'tegen', pl: 'przeciw', uk: 'проти', vi: 'phản đối', bn: 'বিরোধিতা', fa: 'مخالف' },
  context:     { de: 'Hintergrund', en: 'Context', es: 'Contexto', fr: 'Contexte', pt: 'Contexto', ar: 'السياق', zh: '背景', ja: '背景', hi: 'संदर्भ', ru: 'Контекст', id: 'Konteks', tr: 'Bağlam', ko: '맥락', it: 'Contesto', nl: 'Context', pl: 'Kontekst', uk: 'Контекст', vi: 'Bối cảnh', bn: 'প্রসঙ্গ', fa: 'زمینه' },
  voices:      { de: 'digitale Zwillinge', en: 'digital twins', es: 'gemelos digitales', fr: 'jumeaux numériques', pt: 'gêmeos digitais', ar: 'توائم رقمية', zh: '数字孪生', ja: 'デジタルツイン', hi: 'डिजिटल जुड़वां', ru: 'цифровых двойников', id: 'kembaran digital', tr: 'dijital ikiz', ko: '디지털 트윈', it: 'gemelli digitali', nl: 'digitale tweelingen', pl: 'cyfrowych bliźniaków', uk: 'цифрових двійників', vi: 'sinh đôi kỹ thuật số', bn: 'ডিজিটাল যমজ', fa: 'دوقلوی دیجیتال' },
  all_q:       { de: 'Alle Fragen', en: 'All questions', es: 'Todas las preguntas', fr: 'Toutes les questions', pt: 'Todas as perguntas', ar: 'جميع الأسئلة', zh: '所有问题', ja: 'すべての質問', hi: 'सभी प्रश्न', ru: 'Все вопросы', id: 'Semua pertanyaan', tr: 'Tüm sorular', ko: '모든 질문', it: 'Tutte le domande', nl: 'Alle vragen', pl: 'Wszystkie pytania', uk: 'Всі питання', vi: 'Tất cả câu hỏi', bn: 'সব প্রশ্ন', fa: 'همه سؤالات' },
  category:    { de: 'Kategorie', en: 'Category', es: 'Categoría', fr: 'Catégorie', pt: 'Categoria', ar: 'الفئة', zh: '类别', ja: 'カテゴリー', hi: 'श्रेणी', ru: 'Категория', id: 'Kategori', tr: 'Kategori', ko: '카테고리', it: 'Categoria', nl: 'Categorie', pl: 'Kategoria', uk: 'Категорія', vi: 'Danh mục', bn: 'বিভাগ', fa: 'دسته‌بندی' },
  train_cta:   { de: 'Erstelle deinen Zwilling →', en: 'Create your twin →', es: 'Crea tu gemelo →', fr: 'Crée ton jumeau →', pt: 'Crie seu gêmeo →', ar: 'أنشئ توأمك ←', zh: '创建你的孪生 →', ja: 'ツインを作成 →', hi: 'अपना जुड़वां बनाएं →', ru: 'Создай двойника →', id: 'Buat kembaranmu →', tr: 'İkizini oluştur →', ko: '트윈 만들기 →', it: 'Crea il tuo gemello →', nl: 'Maak je tweeling →', pl: 'Utwórz bliźniaka →', uk: 'Створи двійника →', vi: 'Tạo sinh đôi →', bn: 'যমজ তৈরি করুন →', fa: 'دوقلوی خود را بسازید ←' },
  by_archetype:{ de: 'Nach politischem Profil', en: 'By political profile', es: 'Por perfil político', fr: 'Par profil politique', pt: 'Por perfil político', ar: 'حسب الملف السياسي', zh: '按政治档案', ja: '政治プロフィール別', hi: 'राजनीतिक प्रोफ़ाइल के अनुसार', ru: 'По политическому профилю', id: 'Berdasarkan profil politik', tr: 'Siyasi profile göre', ko: '정치 프로필별', it: 'Per profilo politico', nl: 'Op politiek profiel', pl: 'Według profilu politycznego', uk: 'За політичним профілем', vi: 'Theo hồ sơ chính trị', bn: 'রাজনৈতিক প্রোফাইল অনুযায়ী', fa: 'بر اساس پروفایل سیاسی' },
};


